config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, except: %i[new create edit update destroy] do
    resources :blogs
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin_role.name == 'super_admin'
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/admin_role.rb
class AdminRole < ApplicationRecord

  has_many :admin_users

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
    :recoverable,
    :rememberable,
    :validatable

  belongs_to :admin_role

  after_create { |admin| admin.send_reset_password_instructions }

  def password_required?
    new_record? ? false : super
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable

  validates :email, uniqueness: true

  has_many :blogs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Provides the path to redirect after sign in.
  #
  # @params resource [Object<User]
  def after_sign_in_path_for(resource)
    if resource.is_a?(AdminUser)
      super
    else
      user_path(resource) || root_path
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_blog, :redirect_if_unathorized!, only: %i[show edit update destroy]

  # Renders the User blogs.
  def index
    @blogs = current_user.blogs
  end

  def show
  end

  # Renders the new blog form.
  #
  # *Verb:* GET
  #
  # @accepts HTML
  def new
    @blog = current_user.blogs.new
  end

  def edit
  end

  # Creates a new blog for user.
  #
  # *Verb:* POST
  #
  # @post_params params [Hash]
  #  * :title [String]
  #  * :body [String]
  #  * :user_id [String]
  #
  # @accepts HTML, JSON
  def create
    @blog = current_user.blogs.new(blog_params)

    if @blog.save
      flash[:notice] = 'Blog was successfully created.'
      redirect_to user_blog_path(current_user, @blog)
    else
      flash[:notice] = 'Please try again later.'
      render :new, status: :unprocessable_entity
    end
  end

  # Updates the blog for user.
  #
  # *Verb:* POST
  #
  # @post_params params [Hash]
  #  * :title [String]
  #  * :body [String]
  #  * :user_id [String]
  #
  # @accepts HTML, JSON
  def update
    if @blog.update_attributes(blog_params)
      flash[:notice] = 'Blog was successfully updated.'
      redirect_to user_blog_path(current_user, @blog)
    else
      flash[:notice] = 'Please try again later.'
      render :edit, status: :unprocessable_entity
    end
  end

  # Destroy user blogs.
  #
  # *Verb:* DELETE
  #
  # @accepts HTML, JSON
  def destroy
    if @blog.destroy
      flash[:notice] = 'Blog was successfully destroyed.'
      redirect_to user_blogs_path(current_user)
    else
      flash[:notice] = 'Please try again later.'
      render :index
    end
  end

  private

  def set_blog
    @blog = Blog.find_by(id: params[:id]) if params[:id].present?
  end

  # Redirect the user if the Blog is not present or belongs to other user.
  def redirect_if_unathorized!
    return if @blog.present? && @blog.user == current_user

    flash[:notice] = 'Unathorized Access.'
    redirect_to user_blogs_path(current_user)
  end

  # Whitelisted parameters for Blog.
  def blog_params
    params.require(:blog).permit(
      :title, :body
    )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # Renders the home page.
  #
  # *Verb:* GET
  #
  # @accepts HTML
  def index
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # Returns the path to redirect after sign up.
  def after_sign_up_path_for(resource)
    user_blogs_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  # Renders <tt>User</tt> details page.
  #
  # *Verb:* Get
  #
  # @get_params params [Hash]
  #   :id [String]
  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def form_url(blog)
    params[:action] == 'new' ? user_blogs_path(current_user) : user_blog_path(current_user, @blog)
  end

end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, url: form_url(blog)) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %><br />
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', user_blog_path(current_user, @blog) %> |
<%= link_to 'Back', user_blogs_path(current_user) %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td>
          <%= blog.title %>
        </td>
        <td>
          <%= blog.body %>
        </td>
        <td>
          <%= link_to 'Show', user_blog_path(current_user, blog) %>
        </td>
        <td>
          <%= link_to 'Edit', edit_user_blog_path(current_user, blog) %>
        </td>
        <td>
          <%= link_to 'Destroy', user_blog_path(current_user, blog),
          method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_user_blog_path(current_user) %>

<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', user_blogs_path(current_user) %>

app/views/blogs/show.html.erb
<h4>Title: </h4>
  <p><%= @blog.title %></p>
<h4>Body: </h4>
  <p><%= @blog.body %></p>

<%= link_to 'Edit', edit_user_blog_path(current_user, @blog) %> |
<%= link_to 'Back', user_blogs_path(current_user) %>

app/views/home/index.html.erb
<h4>Welcome</h4>
<% if user_signed_in? %>
  <p> Hello <%= current_user.email %>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
  <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h4>This is <%= current_user.email %> </h4>

<%= link_to 'Blogs', user_blogs_path(current_user) %>